import { AppStep } from './types';

export const APP_STEPS_GH: Record<string, AppStep> = {
  LANDING_GH: AppStep.LANDING_GH,
  QUIZ_MULTI_STEP_GH: AppStep.QUIZ_MULTI_STEP_GH,
  ANALYSIS_LOADING_GH: AppStep.ANALYSIS_LOADING_GH,
  PERSONALIZED_RESULTS_GH: AppStep.PERSONALIZED_RESULTS_GH,
  PLANS_DISPLAY_GH: AppStep.PLANS_DISPLAY_GH,
};
